@extends('layouts.app')

@section('content')

    <x-breadcrumbs :links="[
            ['label' => 'Privacy Policy'],
        ]" />

    <article class="mx-auto w-full max-w-4xl pb-24">
        <header class="mb-12 border-t-8 border-[var(--color-text-primary)] border-b-2 border-[var(--color-border)] pt-8 pb-8">
            <div class="mb-4 flex items-center gap-3">
                <span class="h-px w-8 bg-[var(--color-accent-secondary)]"></span>
                <p class="text-[10px] font-black uppercase tracking-[0.25em] text-[var(--color-accent-secondary)]">Legalitas & Informasi</p>
            </div>
            <h1 class="text-4xl font-black uppercase leading-tight tracking-tight text-[var(--color-text-primary)] md:text-6xl">Privacy Policy</h1>
            <p class="mt-4 text-xs font-black tracking-widest uppercase text-[var(--color-text-secondary)] opacity-60">Pembaruan Terakhir: 29 April 2026</p>
        </header>

        <div class="static-page-prose md:text-lg">
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
                information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the
                collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been
                created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/"
                    target="_blank">Privacy Policy Generator</a>.</p>
            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The
                following definitions shall have the same meaning regardless of whether they appear in singular or in
                plural.</p>
            <h3>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
                <li>
                    <strong>Account</strong> means a unique account created for You to access our Service or parts of our
                    Service.
                </li>
                <li>
                    <strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common
                    control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity
                    interest or other securities entitled to vote for election of directors or other managing authority.
                </li>
                <li>
                    <strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;,
                    &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to Goalpedia.
                </li>
                <li>
                    <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other
                    device by a website, containing the details of Your browsing history on that website among its many
                    uses.
                </li>
                <li>
                    <strong>Country</strong> refers to: Indonesia
                </li>
                <li>
                    <strong>Device</strong> means any device that can access the Service such as a computer, a cell phone
                    or a digital tablet.
                </li>
                <li>
                    <strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates
                    to an identified or identifiable individual.
                </li>
                <li>
                    <strong>Service</strong> refers to the Website.
                </li>
                <li>
                    <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf
                    of the Company. It refers to third-party companies or individuals employed by the Company to
                    facilitate the Service, to provide the Service on behalf of the Company, to perform services related
                    to the Service or to assist the Company in analyzing how the Service is used.
                </li>
                <li>
                    <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of
                    the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                </li>
                <li>
                    <strong>Website</strong> refers to Goalpedia, accessible from <a
                        href="https://goalpedia.fauzantaslim.biz.id" rel="external nofollow noopener"
                        target="_blank">https://goalpedia.fauzantaslim.biz.id</a>.
                </li>
                <li>
                    <strong>You</strong> means the individual accessing or using the Service, or the company, or other
                    legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                </li>
            </ul>

            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>
            <h4>Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that
                can be used to contact or identify You. Personally identifiable information may include, but is not limited
                to:</p>
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
            </ul>

            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser
                type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time
                spent on those pages, unique device identifiers and other diagnostic data.</p>

            <h4>Tracking Technologies and Cookies</h4>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
                information. Tracking technologies We use include beacons, tags, and scripts to collect and track
                information and to improve and analyze Our Service.</p>
            <ul>
                <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can
                    instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
                <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small
                    electronic files known as web beacons that permit the Company, for example, to count users who have visited those pages.</li>
            </ul>

            <h3>Use of Your Personal Data</h3>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
                <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract.</li>
                <li><strong>To contact You:</strong> By email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
            </ul>

            <h3>Retention of Your Personal Data</h3>
            <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this
                Privacy Policy.</p>
            <ul>
                <li>User Accounts: up to 24 months after closure.</li>
                <li>Customer Support Data: up to 24 months.</li>
                <li>Usage Data: up to 24 months.</li>
            </ul>

            <h3>Security of Your Personal Data</h3>
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the
                Internet, or method of electronic storage is 100% secure.</p>

            <h2>Children's Privacy</h2>
            <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable
                information from anyone under the age of 16.</p>

            <h2>Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul>
                <li>
                    By email: <a href="mailto:contact@goalpedia.fauzantaslim.biz.id">contact@goalpedia.fauzantaslim.biz.id</a>
                </li>
                <li>
                    By visiting: <a href="https://goalpedia.fauzantaslim.biz.id/kontak"
                        target="_blank">https://goalpedia.fauzantaslim.biz.id/kontak</a>
                </li>
            </ul>
        </div>


    </article>

@endsection
